### ISSUE TITLE
讨论： 事件回调增加 event name 作为签名

### ISSUE THREAD

**Issue by iamthekk** [CatLib/Framework#60]
Hi All:
目前事件回调机制为：
`App.On(string eventName, Action<object> handler, int life = 0);`

在coding中，希望能打印每个事件名称，方便追踪。

也就是说，接口能否改为
`App.On(string eventName, Action<string,object> handler, int life = 0);`

请大伙赐教。

**Comment by yb199478** [comment]
我觉得这个意义不是特别大。
首先，你可以通过参数`payload`定义并传递自己的数据结构，里面完全可以自己实现获取`eventName`，如：
```csharp
public sealed class PayLoad{
    public string EventName{ get; set; }
    public object Data{ get; set; }
}
```

其次，`App.On("*", (payload)=>{ });` 没有必要知晓`eventName`，如果要针对具体的`eventName`做具体的事情为什么不去使用监听事件名的事件呢？而使用通配来匹配事件。

所以综合考虑我们觉得这个不是特别有必要，而且就现有的接口已经可以满足额外的拓展需求。

望讨论，thk~
